############################################################################
## SONOS
############################################################################
# Scripts
############################################################################
script:
  volym_null_sonos:
    alias: "Set SONOS Volume to Zero"
    sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.sonos_living_room
        volume_level: 0.0
#-------------------------------------------------
  volym_normal_sonos:
    alias: "Set SONOS Volume to Normal"
    sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.sonos_living_room
        volume_level: 0.12
############################################################################
# Sensors
############################################################################
sensor:
  - platform: template
    sensors:
      sonos_volume_level:
        friendly_name: "Volym"
        value_template: "{{ ((state_attr('media_player.sonos_living_room', 'volume_level') * 100)|round (0))|int}}"
