title: Home Control Panel
resources:
  - url: /customcards/card-tools.js
    type: js
  - url: /customcards/card-modder.js
    type: js
  - url: /customcards/compact-custom-header.js
    type: module
  - url: /customcards/state-switch.js
    type: js
  - url: /customcards/tracker-card.js
  type: js

views:
  - !include remote.yaml
  
